# Generated by Django 5.1.3 on 2024-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Pendiente', 'Pendiente')], default='Activo', max_length=50),
        ),
    ]
